[package]
name = "spicy-format"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter-spicy = { git = "https://github.com/bbannier/tree-sitter-spicy" }
topiary-core = { git = "https://github.com/tweag/topiary.git", version = "0.3.0" }
topiary-tree-sitter-facade = { git = "https://github.com/tweag/topiary.git", version = "0.3.0" }
tree-sitter-facade = { git = "https://github.com/tweag/tree-sitter-facade" }
clap = { version = "4.5.4", features = ["std", "derive", "help"], default-features = false }
tree-sitter = "0.22.6"
thiserror = "1.0.60"
miette = { version = "7.2.0", default-features = false, features = ["derive", "fancy"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
rayon = "1.10.0"
walkdir = "2.5.0"

[build-dependencies]
vergen = { version = "8.3.1", default-features = false, features = ["git", "gitcl"] }

[profile.release]
panic = "abort"
strip = true
codegen-units = 1
lto = "thin"
